# -*- coding: utf-8 -*-
"""Updated Global sustainable energy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gP8SRHGNNJnEigA_99Qo9VJdEE05LCd2
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter  # Added for GDP formatting
import os
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.ensemble import RandomForestRegressor  # Added for advanced modeling
import plotly.express as px  # For interactive maps and plots

# Fetch latest OWID energy data (updated as of July 2025)
updated_url = 'https://nyc3.digitaloceanspaces.com/owid-public/data/energy/owid-energy-data.csv'
try:
    df_updated = pd.read_csv(updated_url)
    # Rename columns to match original
    rename_dict = {
        'country': 'Entity',
        'year': 'Year',
        'electricity_access': 'Access to electricity (% of population)',
        'clean_fuels_access': 'Access to clean fuels for cooking',
        'renewables_capacity_per_capita': 'Renewable-electricity-generating-capacity-per-capita',
        'financial_flows': 'Financial flows to developing countries (US $)',
        'renewables_share_energy': 'Renewable energy share in the total final energy consumption (%)',
        'fossil_electricity': 'Electricity from fossil fuels (TWh)',
        'nuclear_electricity': 'Electricity from nuclear (TWh)',
        'renewables_electricity': 'Electricity from renewables (TWh)',
        'low_carbon_share_elec': 'Low-carbon electricity (% electricity)',
        'energy_per_capita': 'Primary energy consumption per capita (kWh/person)',
        'energy_intensity': 'Energy intensity level of primary energy (MJ/$2017 PPP GDP)',
        'co2': 'Value_co2_emissions_kt_by_country',
        'renewables_share_eq': 'Renewables (% equivalent primary energy)',
        'gdp_growth': 'gdp_growth',
        'gdp_per_capita': 'gdp_per_capita',
        # Add more if needed; population for density if land_area available
    }
    df_updated = df_updated.rename(columns=rename_dict)
    # Select only matching columns to avoid extras
    matching_cols = list(rename_dict.values()) + ['population']  # Add population for density if needed
    df_updated = df_updated[[col for col in matching_cols if col in df_updated.columns]]
except Exception as e:
    print(f"Error fetching updated data: {e}. Using original data only.")
    df_updated = pd.DataFrame()  # Empty if fail

# Load original cleaned dataset
file_path = 'cleaned_energy_data.csv'  # Update to '/content/cleaned_energy_data.csv' 
try:
    df_original = pd.read_csv(file_path)
except FileNotFoundError:
    print(f"Error: File {file_path} not found. Please upload to Colab.")
    raise

# Merge/append updated data (keep original geo fields like Lat/Long)
if 'Year' in df_updated.columns:
    # Only merge if the updated data fetch was successful and contains the 'Year' column
    df = pd.concat([df_original, df_updated[df_updated['Year'] > 2020]], ignore_index=True)
    print("Successfully merged updated data for years > 2020.")
else:
    # If the fetch failed or was incomplete, use only the original cleaned data
    df = df_original.copy()
    print("WARNING: Using ONLY the static 'cleaned_energy_data.csv' due to updated data fetch failure.")

# If density needed and land_area in original, calculate for new rows (assume constant land_area per country)
if 'Land Area(Km2)' in df.columns and 'population' in df.columns:
    df['Density\n(P/Km2)'] = df.groupby('Entity')['population'].transform('first') / df.groupby('Entity')['Land Area(Km2)'].transform('first')

# Quick verification
print("First 5 rows:")
print(df.head())
print("\nData info:")
print(df.info())
print("\nBasic statistics:")
print(df.describe())
print("\nMissing values:")
print(df.isnull().sum())

# Ensure 'Year' is datetime and add 'YearNum'
df['Year'] = pd.to_datetime(df['Year'], errors='coerce')  # Handle any invalid dates
df['YearNum'] = df['Year'].dt.year

# Select numeric columns for analysis
numeric_cols = df.select_dtypes(include=[np.number]).columns

# Safe remove 'YearNum' if present
if 'YearNum' in numeric_cols:
    numeric_cols = numeric_cols.drop('YearNum')

# Create aggregated dataframes
time_series_data = df.groupby('YearNum')[numeric_cols].mean().reset_index()
country_avg = df.groupby('Entity').mean(numeric_only=True).reset_index()

# Verify aggregated data
print("Time series data preview:")
print(time_series_data.head())
print(f"Total years: {len(time_series_data)}")
print("Country averages preview:")
print(country_avg.head())

# Optional: Outlier removal (e.g., for fossil fuels, 3 std devs)
mean_val = df['Electricity from fossil fuels (TWh)'].mean()
std_val = df['Electricity from fossil fuels (TWh)'].std()
df = df[df['Electricity from fossil fuels (TWh)'].between(mean_val - 3*std_val, mean_val + 3*std_val)]
print(f"Rows after outlier removal: {len(df)}")

# Create visualizations directory if needed
if not os.path.exists('visualizations'):
    os.makedirs('visualizations')

# Box plot for fossil fuels
plt.figure(figsize=(10, 6))
sns.boxplot(x=df['Electricity from fossil fuels (TWh)'])
plt.title('Box Plot of Electricity from Fossil Fuels (TWh)')
plt.savefig('visualizations/fossil_fuel_outliers.png')
plt.show()

# Box plot for CO2 emissions
plt.figure(figsize=(10, 6))
sns.boxplot(x=df['Value_co2_emissions_kt_by_country'])
plt.title('Box Plot of CO2 Emissions (kt by Country)')
plt.savefig('visualizations/co2_emissions_outliers.png')
plt.show()

# Dynamic min/max years
min_year = time_series_data['YearNum'].min()
max_year = time_series_data['YearNum'].max()

# Interactive line plot for renewable vs. fossil
fig = px.line(time_series_data, x='YearNum', y=['Renewable energy share in the total final energy consumption (%)', 'Electricity from fossil fuels (TWh)'],
              title=f'Global Renewable vs. Fossil Fuel Trends ({min_year}-{max_year})', labels={'value': 'Value'})
fig.update_layout(xaxis_title='Year', yaxis_title='Value')
fig.write_html('visualizations/renewable_fossil_trends.html')
fig.show()

# Interactive line plot for CO2 vs. GDP growth
fig = px.line(time_series_data, x='YearNum', y=['Value_co2_emissions_kt_by_country', 'gdp_growth'],
              title=f'Global CO2 Emissions vs. GDP Growth Trends ({min_year}-{max_year})', labels={'value': 'Value'})
fig.update_layout(xaxis_title='Year', yaxis_title='Value')
fig.write_html('visualizations/co2_vs_gdp_trends.html')
fig.show()

# Top 10 by renewable share
top_countries_renewable = country_avg.nlargest(10, 'Renewable energy share in the total final energy consumption (%)')
plt.figure(figsize=(12, 6))
sns.barplot(data=top_countries_renewable, x='Entity', y='Renewable energy share in the total final energy consumption (%)', color='#1f77b4', errorbar='sd')
plt.title(f'Top 10 Countries by Average Renewable Energy Share ({min_year}-{max_year})')
plt.xlabel('Country')
plt.ylabel('Renewable Share (%)')
plt.xticks(rotation=45)
plt.savefig('visualizations/top_renewable_countries.png')
plt.show()

# Top 10 by CO2 emissions
top_countries_co2 = country_avg.nlargest(10, 'Value_co2_emissions_kt_by_country')
plt.figure(figsize=(12, 6))
sns.barplot(data=top_countries_co2, x='Entity', y='Value_co2_emissions_kt_by_country', color='#ff7f0e', errorbar='sd')
plt.title(f'Top 10 Countries by Average CO2 Emissions (kt, {min_year}-{max_year})')
plt.xlabel('Country')
plt.ylabel('CO2 Emissions (kt)')
plt.xticks(rotation=45)
plt.savefig('visualizations/top_co2_countries.png')
plt.show()

# Key columns with safe filter
key_cols = ['Renewable energy share in the total final energy consumption (%)', 'Electricity from fossil fuels (TWh)',
            'Electricity from renewables (TWh)', 'Value_co2_emissions_kt_by_country', 'gdp_per_capita',
            'Energy intensity level of primary energy (MJ/$2017 PPP GDP)', 'Primary energy consumption per capita (kWh/person)']
key_cols = [col for col in key_cols if col in df.columns]

plt.figure(figsize=(10, 6))
sns.heatmap(df[key_cols].corr(method='spearman'), annot=True, cmap='coolwarm', vmin=-1, vmax=1)  # Switched to Spearman for robustness
plt.title('Correlation Heatmap of Key Energy Metrics')
plt.savefig('visualizations/correlation_heatmap.png')
plt.show()

# CO2 vs Renewable (using averages)
fig, ax1 = plt.subplots(figsize=(14, 8))
country_avg_sorted = country_avg.sort_values('Value_co2_emissions_kt_by_country', ascending=False).head(15)
color = 'tab:red'
ax1.set_xlabel('Country', fontsize=13, fontweight='bold')
ax1.set_ylabel('CO₂ Emissions (thousand tonnes)', color=color, fontsize=13, fontweight='bold')
bars = ax1.bar(country_avg_sorted['Entity'], country_avg_sorted['Value_co2_emissions_kt_by_country'], color=color, alpha=0.7, label='CO₂ Emissions')
ax1.tick_params(axis='y', labelcolor=color)
ax1.tick_params(axis='x', rotation=45)
ax2 = ax1.twinx()
color = 'tab:green'
ax2.set_ylabel('Renewable Energy Share (%)', color=color, fontsize=13, fontweight='bold')
line = ax2.plot(country_avg_sorted['Entity'], country_avg_sorted['Renewable energy share in the total final energy consumption (%)'], color=color, marker='o', linewidth=3, markersize=8, label='Renewable Share')
ax2.tick_params(axis='y', labelcolor=color)
plt.title(f'CO₂ Emissions vs Renewable Energy Share\nTop 15 Countries by Average Emissions ({min_year}-{max_year})', fontsize=16, fontweight='bold', pad=20)
ax1.grid(True, alpha=0.3, linestyle='--', linewidth=0.5, axis='y')
ax1.legend(loc='upper left')
ax2.legend(loc='upper right')
plt.tight_layout()
plt.savefig('visualizations/renewable_vs_emissions.png', dpi=300, bbox_inches='tight')
plt.show()

# GDP vs Electricity Access (using averages)
fig, ax1 = plt.subplots(figsize=(14, 8))
country_avg_sorted = country_avg.sort_values('gdp_per_capita', ascending=False).head(15)
color = 'tab:blue'
ax1.set_xlabel('Country', fontsize=13, fontweight='bold')
ax1.set_ylabel('GDP per Capita (USD)', color=color, fontsize=13, fontweight='bold')
bars = ax1.bar(country_avg_sorted['Entity'], country_avg_sorted['gdp_per_capita'], color=color, alpha=0.7, label='GDP per Capita')
ax1.tick_params(axis='y', labelcolor=color)
ax1.tick_params(axis='x', rotation=45)
ax1.yaxis.set_major_formatter(FuncFormatter(lambda x, p: f'${int(x):,}'))
ax2 = ax1.twinx()
color = 'tab:orange'
ax2.set_ylabel('Access to Electricity (% of population)', color=color, fontsize=13, fontweight='bold')
line = ax2.plot(country_avg_sorted['Entity'], country_avg_sorted['Access to electricity (% of population)'], color=color, marker='o', linewidth=3, markersize=8, label='Electricity Access')
ax2.tick_params(axis='y', labelcolor=color)
plt.title(f'GDP per Capita vs Access to Electricity\nTop 15 Countries by Average GDP ({min_year}-{max_year})', fontsize=16, fontweight='bold', pad=20)
ax1.grid(True, alpha=0.3, linestyle='--', linewidth=0.5, axis='y')
ax1.legend(loc='upper left')
ax2.legend(loc='upper right')
plt.tight_layout()
plt.savefig('visualizations/gdp_vs_electricity_access.png', dpi=300, bbox_inches='tight')
plt.show()

# Choropleth for renewable share
fig = px.choropleth(country_avg, locations='Entity', locationmode='country names',
                    color='Renewable energy share in the total final energy consumption (%)',
                    hover_name='Entity', color_continuous_scale='Greens',
                    title=f'Average Renewable Energy Share by Country ({min_year}-{max_year})')
fig.update_layout(geo=dict(showframe=False, showcoastlines=False, projection_type='equirectangular'))
fig.write_html('visualizations/renewable_share_map.html')
fig.show()

# Scatter geo for CO2
# Handle missing values in gdp_per_capita by filling with the mean
country_avg['gdp_per_capita'] = country_avg['gdp_per_capita'].fillna(country_avg['gdp_per_capita'].mean())

fig = px.scatter_geo(country_avg, locations='Entity', locationmode='country names',
                     lat='Latitude' if 'Latitude' in country_avg.columns else None, lon='Longitude' if 'Longitude' in country_avg.columns else None,
                     color='Value_co2_emissions_kt_by_country', size='gdp_per_capita',
                     hover_name='Entity', projection='natural earth',
                     title=f'CO2 Emissions by Country (Bubble Size: GDP per Capita, {min_year}-{max_year} Averages)')
fig.update_layout(geo=dict(showframe=False, showcoastlines=True))
fig.write_html('visualizations/co2_emissions_map.html')
fig.show()

# Choropleth for energy intensity
fig = px.choropleth(country_avg, locations='Entity', locationmode='country names',
                    color='Energy intensity level of primary energy (MJ/$2017 PPP GDP)',
                    hover_name='Entity', color_continuous_scale='Reds',
                    title=f'Average Energy Intensity by Country ({min_year}-{max_year})')
fig.update_layout(geo=dict(showframe=False, showcoastlines=False, projection_type='equirectangular'))
fig.write_html('visualizations/energy_intensity_map.html')
fig.show()

# Prepare data
X = df[['YearNum', 'Electricity from fossil fuels (TWh)', 'Value_co2_emissions_kt_by_country', 'gdp_per_capita']]  # Added gdp_per_capita for better fit
y = df['Renewable energy share in the total final energy consumption (%)']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Handle missing values by filling with the mean
X_train = X_train.fillna(X_train.mean())
X_test = X_test.fillna(X_test.mean())
y_train = y_train.fillna(y_train.mean())
y_test = y_test.fillna(y_test.mean())

# Handle missing values in original X and y for cross-validation
X = X.fillna(X.mean())
y = y.fillna(y.mean())

# Linear model
model = LinearRegression()
model.fit(X_train, y_train)
print(f"Linear R² Score: {model.score(X_test, y_test):.2f}")

# Cross-validation
scores = cross_val_score(model, X, y, cv=5)
print(f"Cross-validated R² Scores: {scores.mean():.2f} (+/- {scores.std() * 2:.2f})")

# Polynomial model
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)
model_poly = LinearRegression()
model_poly.fit(X_train_poly, y_train)
print(f"Polynomial R² Score: {model_poly.score(X_test_poly, y_test):.2f}")

# Random Forest (added for improvement)
rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)
print(f"Random Forest R² Score: {rf.score(X_test, y_test):.2f}")

# Predict for 2030 using mean values (use recent means from last 5 years for realism)
recent_df = df[df['YearNum'] >= df['YearNum'].max() - 4]  # Last 5 years
prediction_data = pd.DataFrame({
    'YearNum': [2030],
    'Electricity from fossil fuels (TWh)': [recent_df['Electricity from fossil fuels (TWh)'].mean()],
    'Value_co2_emissions_kt_by_country': [recent_df['Value_co2_emissions_kt_by_country'].mean()],
    'gdp_per_capita': [recent_df['gdp_per_capita'].mean()]
})
print(f"Predicted Renewable Share for 2030 (Linear): {model.predict(prediction_data)[0]:.2f}%")

prediction_data_poly = poly.transform(prediction_data)
print(f"Predicted Renewable Share for 2030 (Polynomial): {model_poly.predict(prediction_data_poly)[0]:.2f}%")

print(f"Predicted Renewable Share for 2030 (Random Forest): {rf.predict(prediction_data)[0]:.2f}%")

